// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'review.dart';

// These functions are ignored because they are not marked as `pub`: `new`, `profiled`, `with_listing_cache`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

void setWorkspaceDeadline({required String dir, String? date}) => RustLib
    .instance
    .api
    .crateApiListingSetWorkspaceDeadline(dir: dir, date: date);

Future<RootScreen> listRoot({
  required String root,
  BigInt? nowMs,
  required bool profile,
}) => RustLib.instance.api.crateApiListingListRoot(
  root: root,
  nowMs: nowMs,
  profile: profile,
);

String? deckTitle({required String path}) =>
    RustLib.instance.api.crateApiListingDeckTitle(path: path);

Future<MembersScreen> listMembers({
  required String root,
  required String dir,
  BigInt? nowMs,
  required bool profile,
}) => RustLib.instance.api.crateApiListingListMembers(
  root: root,
  dir: dir,
  nowMs: nowMs,
  profile: profile,
);

class Deadline {
  final String date;
  final PlatformInt64 daysLeft;
  final int ready;
  final int total;

  const Deadline({
    required this.date,
    required this.daysLeft,
    required this.ready,
    required this.total,
  });

  @override
  int get hashCode =>
      date.hashCode ^ daysLeft.hashCode ^ ready.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Deadline &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          daysLeft == other.daysLeft &&
          ready == other.ready &&
          total == other.total;
}

class DeckEntry {
  final String title;
  final String path;
  final bool isWorkspace;
  final bool due;
  final bool canRecognize;
  final bool isTrace;
  final Depth lastDepth;
  final bool mastered;
  final bool examDue;
  final bool hasExam;
  final bool locked;
  final bool progressError;
  final String? icon;
  final int indent;
  final String tree;
  final Deadline? deadline;

  const DeckEntry({
    required this.title,
    required this.path,
    required this.isWorkspace,
    required this.due,
    required this.canRecognize,
    required this.isTrace,
    required this.lastDepth,
    required this.mastered,
    required this.examDue,
    required this.hasExam,
    required this.locked,
    required this.progressError,
    this.icon,
    required this.indent,
    required this.tree,
    this.deadline,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      path.hashCode ^
      isWorkspace.hashCode ^
      due.hashCode ^
      canRecognize.hashCode ^
      isTrace.hashCode ^
      lastDepth.hashCode ^
      mastered.hashCode ^
      examDue.hashCode ^
      hasExam.hashCode ^
      locked.hashCode ^
      progressError.hashCode ^
      icon.hashCode ^
      indent.hashCode ^
      tree.hashCode ^
      deadline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeckEntry &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          path == other.path &&
          isWorkspace == other.isWorkspace &&
          due == other.due &&
          canRecognize == other.canRecognize &&
          isTrace == other.isTrace &&
          lastDepth == other.lastDepth &&
          mastered == other.mastered &&
          examDue == other.examDue &&
          hasExam == other.hasExam &&
          locked == other.locked &&
          progressError == other.progressError &&
          icon == other.icon &&
          indent == other.indent &&
          tree == other.tree &&
          deadline == other.deadline;
}

class MembersScreen {
  final List<DeckEntry> entries;
  final Deadline? deadline;
  final OpenProfile? profile;

  const MembersScreen({required this.entries, this.deadline, this.profile});

  @override
  int get hashCode => entries.hashCode ^ deadline.hashCode ^ profile.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MembersScreen &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          deadline == other.deadline &&
          profile == other.profile;
}

class OpenProfile {
  final BigInt libMs;
  final BigInt candidatesClassified;
  final BigInt manifestReads;
  final BigInt decksLoaded;
  final BigInt prerequisiteLoads;
  final BigInt idScans;
  final BigInt diagramGeometryReads;
  final BigInt storeDocumentsRead;
  final BigInt augmentDocumentsRead;
  final BigInt canonicalizeCalls;
  final BigInt sidecarReads;

  const OpenProfile({
    required this.libMs,
    required this.candidatesClassified,
    required this.manifestReads,
    required this.decksLoaded,
    required this.prerequisiteLoads,
    required this.idScans,
    required this.diagramGeometryReads,
    required this.storeDocumentsRead,
    required this.augmentDocumentsRead,
    required this.canonicalizeCalls,
    required this.sidecarReads,
  });

  @override
  int get hashCode =>
      libMs.hashCode ^
      candidatesClassified.hashCode ^
      manifestReads.hashCode ^
      decksLoaded.hashCode ^
      prerequisiteLoads.hashCode ^
      idScans.hashCode ^
      diagramGeometryReads.hashCode ^
      storeDocumentsRead.hashCode ^
      augmentDocumentsRead.hashCode ^
      canonicalizeCalls.hashCode ^
      sidecarReads.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenProfile &&
          runtimeType == other.runtimeType &&
          libMs == other.libMs &&
          candidatesClassified == other.candidatesClassified &&
          manifestReads == other.manifestReads &&
          decksLoaded == other.decksLoaded &&
          prerequisiteLoads == other.prerequisiteLoads &&
          idScans == other.idScans &&
          diagramGeometryReads == other.diagramGeometryReads &&
          storeDocumentsRead == other.storeDocumentsRead &&
          augmentDocumentsRead == other.augmentDocumentsRead &&
          canonicalizeCalls == other.canonicalizeCalls &&
          sidecarReads == other.sidecarReads;
}

class RootScreen {
  final List<DeckEntry> entries;
  final OpenProfile? profile;

  const RootScreen({required this.entries, this.profile});

  @override
  int get hashCode => entries.hashCode ^ profile.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RootScreen &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          profile == other.profile;
}
