// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'review.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

Deadline? workspaceDeadline({
  required String root,
  required String dir,
  BigInt? nowMs,
}) => RustLib.instance.api.crateApiListingWorkspaceDeadline(
  root: root,
  dir: dir,
  nowMs: nowMs,
);

void setWorkspaceDeadline({required String dir, String? date}) => RustLib
    .instance
    .api
    .crateApiListingSetWorkspaceDeadline(dir: dir, date: date);

List<DeckEntry> listRoot({required String root, BigInt? nowMs}) =>
    RustLib.instance.api.crateApiListingListRoot(root: root, nowMs: nowMs);

List<String> syncConflicts({required String root}) =>
    RustLib.instance.api.crateApiListingSyncConflicts(root: root);

List<DeckEntry> listMembers({
  required String root,
  required String dir,
  BigInt? nowMs,
}) => RustLib.instance.api.crateApiListingListMembers(
  root: root,
  dir: dir,
  nowMs: nowMs,
);

class Deadline {
  final String date;
  final PlatformInt64 daysLeft;
  final int ready;
  final int total;

  const Deadline({
    required this.date,
    required this.daysLeft,
    required this.ready,
    required this.total,
  });

  @override
  int get hashCode =>
      date.hashCode ^ daysLeft.hashCode ^ ready.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Deadline &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          daysLeft == other.daysLeft &&
          ready == other.ready &&
          total == other.total;
}

class DeckEntry {
  final String title;
  final String path;
  final bool isWorkspace;
  final bool due;
  final bool canRecognize;
  final bool isTrace;
  final Depth lastDepth;
  final bool mastered;
  final bool examDue;
  final bool hasExam;
  final bool locked;
  final String? icon;
  final int indent;
  final String tree;
  final Deadline? deadline;

  const DeckEntry({
    required this.title,
    required this.path,
    required this.isWorkspace,
    required this.due,
    required this.canRecognize,
    required this.isTrace,
    required this.lastDepth,
    required this.mastered,
    required this.examDue,
    required this.hasExam,
    required this.locked,
    this.icon,
    required this.indent,
    required this.tree,
    this.deadline,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      path.hashCode ^
      isWorkspace.hashCode ^
      due.hashCode ^
      canRecognize.hashCode ^
      isTrace.hashCode ^
      lastDepth.hashCode ^
      mastered.hashCode ^
      examDue.hashCode ^
      hasExam.hashCode ^
      locked.hashCode ^
      icon.hashCode ^
      indent.hashCode ^
      tree.hashCode ^
      deadline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeckEntry &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          path == other.path &&
          isWorkspace == other.isWorkspace &&
          due == other.due &&
          canRecognize == other.canRecognize &&
          isTrace == other.isTrace &&
          lastDepth == other.lastDepth &&
          mastered == other.mastered &&
          examDue == other.examDue &&
          hasExam == other.hasExam &&
          locked == other.locked &&
          icon == other.icon &&
          indent == other.indent &&
          tree == other.tree &&
          deadline == other.deadline;
}
