// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'sync.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `root`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`

String pairedRootDir({required String support, required String rootId}) =>
    RustLib.instance.api.crateApiSyncPairedRootDir(
      support: support,
      rootId: rootId,
    );

List<String> pairedRecover({required String rootDir}) =>
    RustLib.instance.api.crateApiSyncPairedRecover(rootDir: rootDir);

List<PairedEntryState> pairedEntries({required String rootDir}) =>
    RustLib.instance.api.crateApiSyncPairedEntries(rootDir: rootDir);

List<PushPlanItem> pairedPlanPushes({required String rootDir}) =>
    RustLib.instance.api.crateApiSyncPairedPlanPushes(rootDir: rootDir);

void pairedRecordPush({
  required String rootDir,
  required PushPlanItem item,
  required PushOutcomeDto outcome,
}) => RustLib.instance.api.crateApiSyncPairedRecordPush(
  rootDir: rootDir,
  item: item,
  outcome: outcome,
);

/// Unpacks and lands one pulled entry; runs off the UI isolate (blocking
/// file work, so not `sync`).
Future<PullReportDto> pairedApplyPull({
  required String rootDir,
  required String entry,
  required String zipPath,
}) => RustLib.instance.api.crateApiSyncPairedApplyPull(
  rootDir: rootDir,
  entry: entry,
  zipPath: zipPath,
);

ResolutionDto pairedResolveConflict({
  required String rootDir,
  required String deckId,
  required bool keepPhone,
}) => RustLib.instance.api.crateApiSyncPairedResolveConflict(
  rootDir: rootDir,
  deckId: deckId,
  keepPhone: keepPhone,
);

List<RenamedEntry> pairedTidyRenamed({
  required String rootDir,
  required List<String> listed,
}) => RustLib.instance.api.crateApiSyncPairedTidyRenamed(
  rootDir: rootDir,
  listed: listed,
);

List<String> pairedOrphans({
  required String rootDir,
  required List<String> listed,
}) => RustLib.instance.api.crateApiSyncPairedOrphans(
  rootDir: rootDir,
  listed: listed,
);

String pairedStagingZip({required String rootDir, required String entry}) =>
    RustLib.instance.api.crateApiSyncPairedStagingZip(
      rootDir: rootDir,
      entry: entry,
    );

void pairedRemoveEntry({required String rootDir, required String entry}) =>
    RustLib.instance.api.crateApiSyncPairedRemoveEntry(
      rootDir: rootDir,
      entry: entry,
    );

BigInt pairedFreeSpace({required String path}) =>
    RustLib.instance.api.crateApiSyncPairedFreeSpace(path: path);

BigInt pairedNeedsSpace({
  required BigInt compressed,
  required BigInt unpacked,
}) => RustLib.instance.api.crateApiSyncPairedNeedsSpace(
  compressed: compressed,
  unpacked: unpacked,
);

@freezed
sealed class PairedConflict with _$PairedConflict {
  const PairedConflict._();

  const factory PairedConflict.push({
    BigInt? desktopRevision,
    BigInt? pulledRevision,
    PairedWriter? desktopWriter,
  }) = PairedConflict_Push;
  const factory PairedConflict.pull({
    BigInt? pulledRevision,
    PairedWriter? pulledWriter,
  }) = PairedConflict_Pull;
}

class PairedDeckState {
  final String deckId;
  final String path;
  final bool unpushed;
  final PairedConflict? conflict;

  const PairedDeckState({
    required this.deckId,
    required this.path,
    required this.unpushed,
    this.conflict,
  });

  @override
  int get hashCode =>
      deckId.hashCode ^ path.hashCode ^ unpushed.hashCode ^ conflict.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairedDeckState &&
          runtimeType == other.runtimeType &&
          deckId == other.deckId &&
          path == other.path &&
          unpushed == other.unpushed &&
          conflict == other.conflict;
}

class PairedEntryState {
  final String entry;
  final String kind;
  final List<PairedDeckState> decks;

  const PairedEntryState({
    required this.entry,
    required this.kind,
    required this.decks,
  });

  @override
  int get hashCode => entry.hashCode ^ kind.hashCode ^ decks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairedEntryState &&
          runtimeType == other.runtimeType &&
          entry == other.entry &&
          kind == other.kind &&
          decks == other.decks;
}

class PairedWriter {
  final String device;
  final BigInt atMs;

  const PairedWriter({required this.device, required this.atMs});

  @override
  int get hashCode => device.hashCode ^ atMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairedWriter &&
          runtimeType == other.runtimeType &&
          device == other.device &&
          atMs == other.atMs;
}

class PullReportDto {
  final String entry;
  final String kind;
  final List<String> landed;
  final List<String> kept;
  final List<String> conflicts;
  final List<String> phoneOnly;
  final List<String> removed;

  const PullReportDto({
    required this.entry,
    required this.kind,
    required this.landed,
    required this.kept,
    required this.conflicts,
    required this.phoneOnly,
    required this.removed,
  });

  @override
  int get hashCode =>
      entry.hashCode ^
      kind.hashCode ^
      landed.hashCode ^
      kept.hashCode ^
      conflicts.hashCode ^
      phoneOnly.hashCode ^
      removed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PullReportDto &&
          runtimeType == other.runtimeType &&
          entry == other.entry &&
          kind == other.kind &&
          landed == other.landed &&
          kept == other.kept &&
          conflicts == other.conflicts &&
          phoneOnly == other.phoneOnly &&
          removed == other.removed;
}

@freezed
sealed class PushOutcomeDto with _$PushOutcomeDto {
  const PushOutcomeDto._();

  const factory PushOutcomeDto.accepted({required BigInt revision}) =
      PushOutcomeDto_Accepted;
  const factory PushOutcomeDto.conflict({
    BigInt? desktopRevision,
    PairedWriter? desktopWriter,
  }) = PushOutcomeDto_Conflict;
  const factory PushOutcomeDto.notServed() = PushOutcomeDto_NotServed;
}

class PushPlanItem {
  final String deckId;
  final String entry;
  final String document;
  final BigInt? base;
  final BigInt phoneRevision;

  const PushPlanItem({
    required this.deckId,
    required this.entry,
    required this.document,
    this.base,
    required this.phoneRevision,
  });

  @override
  int get hashCode =>
      deckId.hashCode ^
      entry.hashCode ^
      document.hashCode ^
      base.hashCode ^
      phoneRevision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PushPlanItem &&
          runtimeType == other.runtimeType &&
          deckId == other.deckId &&
          entry == other.entry &&
          document == other.document &&
          base == other.base &&
          phoneRevision == other.phoneRevision;
}

class RenamedEntry {
  final String old;
  final String new_;

  const RenamedEntry({required this.old, required this.new_});

  @override
  int get hashCode => old.hashCode ^ new_.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenamedEntry &&
          runtimeType == other.runtimeType &&
          old == other.old &&
          new_ == other.new_;
}

@freezed
sealed class ResolutionDto with _$ResolutionDto {
  const ResolutionDto._();

  const factory ResolutionDto.done() = ResolutionDto_Done;
  const factory ResolutionDto.push({required PushPlanItem item}) =
      ResolutionDto_Push;
  const factory ResolutionDto.pull({required String entry}) =
      ResolutionDto_Pull;
}
