// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/generate.dart';
import 'api/listing.dart';
import 'api/review.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ReviewSessionPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSessionPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_WalkSessionPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSessionPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ReviewSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    dynamic raw,
  );

  @protected
  WalkSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession(
    dynamic raw,
  );

  @protected
  ReviewSession
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    dynamic raw,
  );

  @protected
  WalkSession
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession(
    dynamic raw,
  );

  @protected
  ReviewSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    dynamic raw,
  );

  @protected
  WalkSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession(
    dynamic raw,
  );

  @protected
  ReviewSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    dynamic raw,
  );

  @protected
  WalkSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CardView dco_decode_box_autoadd_card_view(dynamic raw);

  @protected
  CheckFeedback dco_decode_box_autoadd_check_feedback(dynamic raw);

  @protected
  ChoiceFeedback dco_decode_box_autoadd_choice_feedback(dynamic raw);

  @protected
  CrumbState dco_decode_box_autoadd_crumb_state(dynamic raw);

  @protected
  Deadline dco_decode_box_autoadd_deadline(dynamic raw);

  @protected
  Depth dco_decode_box_autoadd_depth(dynamic raw);

  @protected
  ForeignWriter dco_decode_box_autoadd_foreign_writer(dynamic raw);

  @protected
  TutorCard dco_decode_box_autoadd_tutor_card(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  WalkExcerpt dco_decode_box_autoadd_walk_excerpt(dynamic raw);

  @protected
  WalkSummary dco_decode_box_autoadd_walk_summary(dynamic raw);

  @protected
  CardView dco_decode_card_view(dynamic raw);

  @protected
  CheckFeedback dco_decode_check_feedback(dynamic raw);

  @protected
  ChoiceFeedback dco_decode_choice_feedback(dynamic raw);

  @protected
  CrumbState dco_decode_crumb_state(dynamic raw);

  @protected
  Deadline dco_decode_deadline(dynamic raw);

  @protected
  DeckEntry dco_decode_deck_entry(dynamic raw);

  @protected
  Depth dco_decode_depth(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  ForeignWriter dco_decode_foreign_writer(dynamic raw);

  @protected
  Grade dco_decode_grade(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImageView dco_decode_image_view(dynamic raw);

  @protected
  Input dco_decode_input(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DeckEntry> dco_decode_list_deck_entry(dynamic raw);

  @protected
  List<ImageView> dco_decode_list_image_view(dynamic raw);

  @protected
  List<Float32List> dco_decode_list_list_prim_f_32_strict(dynamic raw);

  @protected
  List<NoteUnit> dco_decode_list_note_unit(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TypedResult> dco_decode_list_typed_result(dynamic raw);

  @protected
  List<WalkLine> dco_decode_list_walk_line(dynamic raw);

  @protected
  Mode dco_decode_mode(dynamic raw);

  @protected
  NoteUnit dco_decode_note_unit(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CardView? dco_decode_opt_box_autoadd_card_view(dynamic raw);

  @protected
  CheckFeedback? dco_decode_opt_box_autoadd_check_feedback(dynamic raw);

  @protected
  ChoiceFeedback? dco_decode_opt_box_autoadd_choice_feedback(dynamic raw);

  @protected
  CrumbState? dco_decode_opt_box_autoadd_crumb_state(dynamic raw);

  @protected
  Deadline? dco_decode_opt_box_autoadd_deadline(dynamic raw);

  @protected
  Depth? dco_decode_opt_box_autoadd_depth(dynamic raw);

  @protected
  ForeignWriter? dco_decode_opt_box_autoadd_foreign_writer(dynamic raw);

  @protected
  TutorCard? dco_decode_opt_box_autoadd_tutor_card(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  WalkExcerpt? dco_decode_opt_box_autoadd_walk_excerpt(dynamic raw);

  @protected
  WalkSummary? dco_decode_opt_box_autoadd_walk_summary(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  ReviewState dco_decode_review_state(dynamic raw);

  @protected
  TutorCard dco_decode_tutor_card(dynamic raw);

  @protected
  TypedResult dco_decode_typed_result(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WalkDelta dco_decode_walk_delta(dynamic raw);

  @protected
  WalkExcerpt dco_decode_walk_excerpt(dynamic raw);

  @protected
  WalkLine dco_decode_walk_line(dynamic raw);

  @protected
  WalkPhase dco_decode_walk_phase(dynamic raw);

  @protected
  WalkState dco_decode_walk_state(dynamic raw);

  @protected
  WalkSummary dco_decode_walk_summary(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ReviewSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    SseDeserializer deserializer,
  );

  @protected
  WalkSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession(
    SseDeserializer deserializer,
  );

  @protected
  ReviewSession
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    SseDeserializer deserializer,
  );

  @protected
  WalkSession
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession(
    SseDeserializer deserializer,
  );

  @protected
  ReviewSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    SseDeserializer deserializer,
  );

  @protected
  WalkSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession(
    SseDeserializer deserializer,
  );

  @protected
  ReviewSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    SseDeserializer deserializer,
  );

  @protected
  WalkSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CardView sse_decode_box_autoadd_card_view(SseDeserializer deserializer);

  @protected
  CheckFeedback sse_decode_box_autoadd_check_feedback(
    SseDeserializer deserializer,
  );

  @protected
  ChoiceFeedback sse_decode_box_autoadd_choice_feedback(
    SseDeserializer deserializer,
  );

  @protected
  CrumbState sse_decode_box_autoadd_crumb_state(SseDeserializer deserializer);

  @protected
  Deadline sse_decode_box_autoadd_deadline(SseDeserializer deserializer);

  @protected
  Depth sse_decode_box_autoadd_depth(SseDeserializer deserializer);

  @protected
  ForeignWriter sse_decode_box_autoadd_foreign_writer(
    SseDeserializer deserializer,
  );

  @protected
  TutorCard sse_decode_box_autoadd_tutor_card(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  WalkExcerpt sse_decode_box_autoadd_walk_excerpt(SseDeserializer deserializer);

  @protected
  WalkSummary sse_decode_box_autoadd_walk_summary(SseDeserializer deserializer);

  @protected
  CardView sse_decode_card_view(SseDeserializer deserializer);

  @protected
  CheckFeedback sse_decode_check_feedback(SseDeserializer deserializer);

  @protected
  ChoiceFeedback sse_decode_choice_feedback(SseDeserializer deserializer);

  @protected
  CrumbState sse_decode_crumb_state(SseDeserializer deserializer);

  @protected
  Deadline sse_decode_deadline(SseDeserializer deserializer);

  @protected
  DeckEntry sse_decode_deck_entry(SseDeserializer deserializer);

  @protected
  Depth sse_decode_depth(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  ForeignWriter sse_decode_foreign_writer(SseDeserializer deserializer);

  @protected
  Grade sse_decode_grade(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImageView sse_decode_image_view(SseDeserializer deserializer);

  @protected
  Input sse_decode_input(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DeckEntry> sse_decode_list_deck_entry(SseDeserializer deserializer);

  @protected
  List<ImageView> sse_decode_list_image_view(SseDeserializer deserializer);

  @protected
  List<Float32List> sse_decode_list_list_prim_f_32_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<NoteUnit> sse_decode_list_note_unit(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TypedResult> sse_decode_list_typed_result(SseDeserializer deserializer);

  @protected
  List<WalkLine> sse_decode_list_walk_line(SseDeserializer deserializer);

  @protected
  Mode sse_decode_mode(SseDeserializer deserializer);

  @protected
  NoteUnit sse_decode_note_unit(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CardView? sse_decode_opt_box_autoadd_card_view(SseDeserializer deserializer);

  @protected
  CheckFeedback? sse_decode_opt_box_autoadd_check_feedback(
    SseDeserializer deserializer,
  );

  @protected
  ChoiceFeedback? sse_decode_opt_box_autoadd_choice_feedback(
    SseDeserializer deserializer,
  );

  @protected
  CrumbState? sse_decode_opt_box_autoadd_crumb_state(
    SseDeserializer deserializer,
  );

  @protected
  Deadline? sse_decode_opt_box_autoadd_deadline(SseDeserializer deserializer);

  @protected
  Depth? sse_decode_opt_box_autoadd_depth(SseDeserializer deserializer);

  @protected
  ForeignWriter? sse_decode_opt_box_autoadd_foreign_writer(
    SseDeserializer deserializer,
  );

  @protected
  TutorCard? sse_decode_opt_box_autoadd_tutor_card(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  WalkExcerpt? sse_decode_opt_box_autoadd_walk_excerpt(
    SseDeserializer deserializer,
  );

  @protected
  WalkSummary? sse_decode_opt_box_autoadd_walk_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  ReviewState sse_decode_review_state(SseDeserializer deserializer);

  @protected
  TutorCard sse_decode_tutor_card(SseDeserializer deserializer);

  @protected
  TypedResult sse_decode_typed_result(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WalkDelta sse_decode_walk_delta(SseDeserializer deserializer);

  @protected
  WalkExcerpt sse_decode_walk_excerpt(SseDeserializer deserializer);

  @protected
  WalkLine sse_decode_walk_line(SseDeserializer deserializer);

  @protected
  WalkPhase sse_decode_walk_phase(SseDeserializer deserializer);

  @protected
  WalkState sse_decode_walk_state(SseDeserializer deserializer);

  @protected
  WalkSummary sse_decode_walk_summary(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    ReviewSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession(
    WalkSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    ReviewSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession(
    WalkSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    ReviewSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession(
    WalkSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    ReviewSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession(
    WalkSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_card_view(
    CardView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_check_feedback(
    CheckFeedback self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_choice_feedback(
    ChoiceFeedback self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_crumb_state(
    CrumbState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_deadline(Deadline self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_depth(Depth self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_foreign_writer(
    ForeignWriter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_tutor_card(
    TutorCard self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_walk_excerpt(
    WalkExcerpt self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_walk_summary(
    WalkSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_card_view(CardView self, SseSerializer serializer);

  @protected
  void sse_encode_check_feedback(CheckFeedback self, SseSerializer serializer);

  @protected
  void sse_encode_choice_feedback(
    ChoiceFeedback self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_crumb_state(CrumbState self, SseSerializer serializer);

  @protected
  void sse_encode_deadline(Deadline self, SseSerializer serializer);

  @protected
  void sse_encode_deck_entry(DeckEntry self, SseSerializer serializer);

  @protected
  void sse_encode_depth(Depth self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_foreign_writer(ForeignWriter self, SseSerializer serializer);

  @protected
  void sse_encode_grade(Grade self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_image_view(ImageView self, SseSerializer serializer);

  @protected
  void sse_encode_input(Input self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_deck_entry(
    List<DeckEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_image_view(
    List<ImageView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_f_32_strict(
    List<Float32List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_note_unit(List<NoteUnit> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_typed_result(
    List<TypedResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_walk_line(List<WalkLine> self, SseSerializer serializer);

  @protected
  void sse_encode_mode(Mode self, SseSerializer serializer);

  @protected
  void sse_encode_note_unit(NoteUnit self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_card_view(
    CardView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_check_feedback(
    CheckFeedback? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_choice_feedback(
    ChoiceFeedback? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_crumb_state(
    CrumbState? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_deadline(
    Deadline? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_depth(Depth? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_foreign_writer(
    ForeignWriter? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_tutor_card(
    TutorCard? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_walk_excerpt(
    WalkExcerpt? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_walk_summary(
    WalkSummary? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_review_state(ReviewState self, SseSerializer serializer);

  @protected
  void sse_encode_tutor_card(TutorCard self, SseSerializer serializer);

  @protected
  void sse_encode_typed_result(TypedResult self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_walk_delta(WalkDelta self, SseSerializer serializer);

  @protected
  void sse_encode_walk_excerpt(WalkExcerpt self, SseSerializer serializer);

  @protected
  void sse_encode_walk_line(WalkLine self, SseSerializer serializer);

  @protected
  void sse_encode_walk_phase(WalkPhase self, SseSerializer serializer);

  @protected
  void sse_encode_walk_state(WalkState self, SseSerializer serializer);

  @protected
  void sse_encode_walk_summary(WalkSummary self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_alix_mobile_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_alix_mobile_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_alix_mobile_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_alix_mobile_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSession =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalkSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
