// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/listing.dart';
import 'api/review.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -585242153;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_alix_mobile',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  ReviewState crateApiReviewReviewSessionAcquire({
    required ReviewSession that,
    BigInt? nowMs,
  });

  void crateApiReviewReviewSessionApplyExamPassed({
    required ReviewSession that,
    required BigInt nowMs,
  });

  int crateApiReviewReviewSessionApplyRemediation({
    required ReviewSession that,
    required String cardsText,
    required BigInt nowMs,
  });

  CheckFeedback? crateApiReviewReviewSessionCheck({
    required ReviewSession that,
    required List<String> lines,
  });

  ChoiceFeedback? crateApiReviewReviewSessionChoose({
    required ReviewSession that,
    required int chosen,
  });

  bool crateApiReviewReviewSessionDeckHasExam({required ReviewSession that});

  ForeignWriter? crateApiReviewReviewSessionForeignWriter({
    required ReviewSession that,
    BigInt? nowMs,
  });

  ReviewState crateApiReviewReviewSessionGrade({
    required ReviewSession that,
    required Grade grade,
    BigInt? nowMs,
  });

  String crateApiReviewReviewSessionMintTutorCard({
    required ReviewSession that,
    required String front,
    required List<String> back,
    required BigInt nowMs,
  });

  ReviewSession crateApiReviewReviewSessionOpen({
    required String deckPath,
    required String rootDir,
    Depth? depth,
    BigInt? nowMs,
    String? device,
  });

  ReviewState crateApiReviewReviewSessionState({
    required ReviewSession that,
    BigInt? nowMs,
  });

  TutorCard? crateApiReviewReviewSessionTutorCard({
    required ReviewSession that,
  });

  String crateApiSimpleCoreVersion();

  Future<void> crateApiSimpleInitApp();

  Grade crateApiReviewKeypointGrade({required int covered, required int total});

  List<DeckEntry> crateApiListingListMembers({
    required String root,
    required String dir,
    BigInt? nowMs,
  });

  List<DeckEntry> crateApiListingListRoot({
    required String root,
    BigInt? nowMs,
  });

  List<String> crateApiListingSyncConflicts({required String root});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ReviewSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ReviewSession;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ReviewSessionPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  ReviewState crateApiReviewReviewSessionAcquire({
    required ReviewSession that,
    BigInt? nowMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
            that,
            serializer,
          );
          sse_encode_opt_box_autoadd_u_64(nowMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_review_state,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReviewReviewSessionAcquireConstMeta,
        argValues: [that, nowMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewReviewSessionAcquireConstMeta =>
      const TaskConstMeta(
        debugName: "ReviewSession_acquire",
        argNames: ["that", "nowMs"],
      );

  @override
  void crateApiReviewReviewSessionApplyExamPassed({
    required ReviewSession that,
    required BigInt nowMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
            that,
            serializer,
          );
          sse_encode_u_64(nowMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReviewReviewSessionApplyExamPassedConstMeta,
        argValues: [that, nowMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewReviewSessionApplyExamPassedConstMeta =>
      const TaskConstMeta(
        debugName: "ReviewSession_apply_exam_passed",
        argNames: ["that", "nowMs"],
      );

  @override
  int crateApiReviewReviewSessionApplyRemediation({
    required ReviewSession that,
    required String cardsText,
    required BigInt nowMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
            that,
            serializer,
          );
          sse_encode_String(cardsText, serializer);
          sse_encode_u_64(nowMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReviewReviewSessionApplyRemediationConstMeta,
        argValues: [that, cardsText, nowMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewReviewSessionApplyRemediationConstMeta =>
      const TaskConstMeta(
        debugName: "ReviewSession_apply_remediation",
        argNames: ["that", "cardsText", "nowMs"],
      );

  @override
  CheckFeedback? crateApiReviewReviewSessionCheck({
    required ReviewSession that,
    required List<String> lines,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
            that,
            serializer,
          );
          sse_encode_list_String(lines, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_check_feedback,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReviewReviewSessionCheckConstMeta,
        argValues: [that, lines],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewReviewSessionCheckConstMeta =>
      const TaskConstMeta(
        debugName: "ReviewSession_check",
        argNames: ["that", "lines"],
      );

  @override
  ChoiceFeedback? crateApiReviewReviewSessionChoose({
    required ReviewSession that,
    required int chosen,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
            that,
            serializer,
          );
          sse_encode_u_32(chosen, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_choice_feedback,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReviewReviewSessionChooseConstMeta,
        argValues: [that, chosen],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewReviewSessionChooseConstMeta =>
      const TaskConstMeta(
        debugName: "ReviewSession_choose",
        argNames: ["that", "chosen"],
      );

  @override
  bool crateApiReviewReviewSessionDeckHasExam({required ReviewSession that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReviewReviewSessionDeckHasExamConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewReviewSessionDeckHasExamConstMeta =>
      const TaskConstMeta(
        debugName: "ReviewSession_deck_has_exam",
        argNames: ["that"],
      );

  @override
  ForeignWriter? crateApiReviewReviewSessionForeignWriter({
    required ReviewSession that,
    BigInt? nowMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
            that,
            serializer,
          );
          sse_encode_opt_box_autoadd_u_64(nowMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_foreign_writer,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReviewReviewSessionForeignWriterConstMeta,
        argValues: [that, nowMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewReviewSessionForeignWriterConstMeta =>
      const TaskConstMeta(
        debugName: "ReviewSession_foreign_writer",
        argNames: ["that", "nowMs"],
      );

  @override
  ReviewState crateApiReviewReviewSessionGrade({
    required ReviewSession that,
    required Grade grade,
    BigInt? nowMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
            that,
            serializer,
          );
          sse_encode_grade(grade, serializer);
          sse_encode_opt_box_autoadd_u_64(nowMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_review_state,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReviewReviewSessionGradeConstMeta,
        argValues: [that, grade, nowMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewReviewSessionGradeConstMeta =>
      const TaskConstMeta(
        debugName: "ReviewSession_grade",
        argNames: ["that", "grade", "nowMs"],
      );

  @override
  String crateApiReviewReviewSessionMintTutorCard({
    required ReviewSession that,
    required String front,
    required List<String> back,
    required BigInt nowMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
            that,
            serializer,
          );
          sse_encode_String(front, serializer);
          sse_encode_list_String(back, serializer);
          sse_encode_u_64(nowMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReviewReviewSessionMintTutorCardConstMeta,
        argValues: [that, front, back, nowMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewReviewSessionMintTutorCardConstMeta =>
      const TaskConstMeta(
        debugName: "ReviewSession_mint_tutor_card",
        argNames: ["that", "front", "back", "nowMs"],
      );

  @override
  ReviewSession crateApiReviewReviewSessionOpen({
    required String deckPath,
    required String rootDir,
    Depth? depth,
    BigInt? nowMs,
    String? device,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deckPath, serializer);
          sse_encode_String(rootDir, serializer);
          sse_encode_opt_box_autoadd_depth(depth, serializer);
          sse_encode_opt_box_autoadd_u_64(nowMs, serializer);
          sse_encode_opt_String(device, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReviewReviewSessionOpenConstMeta,
        argValues: [deckPath, rootDir, depth, nowMs, device],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewReviewSessionOpenConstMeta =>
      const TaskConstMeta(
        debugName: "ReviewSession_open",
        argNames: ["deckPath", "rootDir", "depth", "nowMs", "device"],
      );

  @override
  ReviewState crateApiReviewReviewSessionState({
    required ReviewSession that,
    BigInt? nowMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
            that,
            serializer,
          );
          sse_encode_opt_box_autoadd_u_64(nowMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_review_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReviewReviewSessionStateConstMeta,
        argValues: [that, nowMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewReviewSessionStateConstMeta =>
      const TaskConstMeta(
        debugName: "ReviewSession_state",
        argNames: ["that", "nowMs"],
      );

  @override
  TutorCard? crateApiReviewReviewSessionTutorCard({
    required ReviewSession that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_tutor_card,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReviewReviewSessionTutorCardConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewReviewSessionTutorCardConstMeta =>
      const TaskConstMeta(
        debugName: "ReviewSession_tutor_card",
        argNames: ["that"],
      );

  @override
  String crateApiSimpleCoreVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleCoreVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCoreVersionConstMeta =>
      const TaskConstMeta(debugName: "core_version", argNames: []);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Grade crateApiReviewKeypointGrade({
    required int covered,
    required int total,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(covered, serializer);
          sse_encode_u_32(total, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_grade,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReviewKeypointGradeConstMeta,
        argValues: [covered, total],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewKeypointGradeConstMeta =>
      const TaskConstMeta(
        debugName: "keypoint_grade",
        argNames: ["covered", "total"],
      );

  @override
  List<DeckEntry> crateApiListingListMembers({
    required String root,
    required String dir,
    BigInt? nowMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          sse_encode_String(dir, serializer);
          sse_encode_opt_box_autoadd_u_64(nowMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_deck_entry,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiListingListMembersConstMeta,
        argValues: [root, dir, nowMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListingListMembersConstMeta => const TaskConstMeta(
    debugName: "list_members",
    argNames: ["root", "dir", "nowMs"],
  );

  @override
  List<DeckEntry> crateApiListingListRoot({
    required String root,
    BigInt? nowMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          sse_encode_opt_box_autoadd_u_64(nowMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_deck_entry,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiListingListRootConstMeta,
        argValues: [root, nowMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListingListRootConstMeta =>
      const TaskConstMeta(debugName: "list_root", argNames: ["root", "nowMs"]);

  @override
  List<String> crateApiListingSyncConflicts({required String root}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiListingSyncConflictsConstMeta,
        argValues: [root],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListingSyncConflictsConstMeta =>
      const TaskConstMeta(debugName: "sync_conflicts", argNames: ["root"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ReviewSession => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ReviewSession => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  ReviewSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReviewSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ReviewSession
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReviewSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ReviewSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReviewSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ReviewSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReviewSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CardView dco_decode_box_autoadd_card_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_card_view(raw);
  }

  @protected
  CheckFeedback dco_decode_box_autoadd_check_feedback(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_check_feedback(raw);
  }

  @protected
  ChoiceFeedback dco_decode_box_autoadd_choice_feedback(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_choice_feedback(raw);
  }

  @protected
  Depth dco_decode_box_autoadd_depth(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_depth(raw);
  }

  @protected
  ForeignWriter dco_decode_box_autoadd_foreign_writer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_foreign_writer(raw);
  }

  @protected
  TutorCard dco_decode_box_autoadd_tutor_card(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_tutor_card(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  CardView dco_decode_card_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return CardView(
      front: dco_decode_String(arr[0]),
      context: dco_decode_list_String(arr[1]),
      back: dco_decode_list_String(arr[2]),
      reshaped: dco_decode_bool(arr[3]),
      note: dco_decode_list_note_unit(arr[4]),
      image: dco_decode_opt_String(arr[5]),
      imageBack: dco_decode_opt_String(arr[6]),
      at: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  CheckFeedback dco_decode_check_feedback(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CheckFeedback(
      results: dco_decode_list_typed_result(arr[0]),
      passed: dco_decode_bool(arr[1]),
    );
  }

  @protected
  ChoiceFeedback dco_decode_choice_feedback(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ChoiceFeedback(
      chosen: dco_decode_usize(arr[0]),
      correct: dco_decode_usize(arr[1]),
      passed: dco_decode_bool(arr[2]),
    );
  }

  @protected
  DeckEntry dco_decode_deck_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DeckEntry(
      title: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      isWorkspace: dco_decode_bool(arr[2]),
      due: dco_decode_bool(arr[3]),
      isTrace: dco_decode_bool(arr[4]),
    );
  }

  @protected
  Depth dco_decode_depth(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Depth.values[raw as int];
  }

  @protected
  ForeignWriter dco_decode_foreign_writer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ForeignWriter(
      device: dco_decode_String(arr[0]),
      ageMs: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  Grade dco_decode_grade(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Grade.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Input dco_decode_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Input.values[raw as int];
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DeckEntry> dco_decode_list_deck_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_deck_entry).toList();
  }

  @protected
  List<NoteUnit> dco_decode_list_note_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_note_unit).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TypedResult> dco_decode_list_typed_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_typed_result).toList();
  }

  @protected
  Mode dco_decode_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Mode.values[raw as int];
  }

  @protected
  NoteUnit dco_decode_note_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return NoteUnit_Sentence(text: dco_decode_String(raw[1]));
      case 1:
        return NoteUnit_Code(lines: dco_decode_list_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  CardView? dco_decode_opt_box_autoadd_card_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_card_view(raw);
  }

  @protected
  CheckFeedback? dco_decode_opt_box_autoadd_check_feedback(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_check_feedback(raw);
  }

  @protected
  ChoiceFeedback? dco_decode_opt_box_autoadd_choice_feedback(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_choice_feedback(raw);
  }

  @protected
  Depth? dco_decode_opt_box_autoadd_depth(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_depth(raw);
  }

  @protected
  ForeignWriter? dco_decode_opt_box_autoadd_foreign_writer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_foreign_writer(raw);
  }

  @protected
  TutorCard? dco_decode_opt_box_autoadd_tutor_card(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_tutor_card(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_String(raw);
  }

  @protected
  ReviewState dco_decode_review_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 16)
      throw Exception('unexpected arr length: expect 16 but see ${arr.length}');
    return ReviewState(
      card: dco_decode_opt_box_autoadd_card_view(arr[0]),
      mode: dco_decode_mode(arr[1]),
      depth: dco_decode_depth(arr[2]),
      acquire: dco_decode_bool(arr[3]),
      choices: dco_decode_opt_list_String(arr[4]),
      keypoints: dco_decode_opt_list_String(arr[5]),
      input: dco_decode_input(arr[6]),
      finished: dco_decode_bool(arr[7]),
      remaining: dco_decode_u_32(arr[8]),
      initial: dco_decode_u_32(arr[9]),
      reviews: dco_decode_u_32(arr[10]),
      passed: dco_decode_u_32(arr[11]),
      failed: dco_decode_u_32(arr[12]),
      acquired: dco_decode_u_32(arr[13]),
      canRestart: dco_decode_bool(arr[14]),
      promotable: dco_decode_bool(arr[15]),
    );
  }

  @protected
  TutorCard dco_decode_tutor_card(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TutorCard(
      subject: dco_decode_String(arr[0]),
      front: dco_decode_String(arr[1]),
      back: dco_decode_list_String(arr[2]),
      at: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  TypedResult dco_decode_typed_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TypedResult(
      input: dco_decode_String(arr[0]),
      expected: dco_decode_String(arr[1]),
      passed: dco_decode_bool(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  ReviewSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ReviewSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ReviewSession
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ReviewSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ReviewSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ReviewSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ReviewSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ReviewSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CardView sse_decode_box_autoadd_card_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_card_view(deserializer));
  }

  @protected
  CheckFeedback sse_decode_box_autoadd_check_feedback(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_check_feedback(deserializer));
  }

  @protected
  ChoiceFeedback sse_decode_box_autoadd_choice_feedback(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_choice_feedback(deserializer));
  }

  @protected
  Depth sse_decode_box_autoadd_depth(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_depth(deserializer));
  }

  @protected
  ForeignWriter sse_decode_box_autoadd_foreign_writer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_foreign_writer(deserializer));
  }

  @protected
  TutorCard sse_decode_box_autoadd_tutor_card(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_tutor_card(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  CardView sse_decode_card_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_front = sse_decode_String(deserializer);
    var var_context = sse_decode_list_String(deserializer);
    var var_back = sse_decode_list_String(deserializer);
    var var_reshaped = sse_decode_bool(deserializer);
    var var_note = sse_decode_list_note_unit(deserializer);
    var var_image = sse_decode_opt_String(deserializer);
    var var_imageBack = sse_decode_opt_String(deserializer);
    var var_at = sse_decode_opt_String(deserializer);
    return CardView(
      front: var_front,
      context: var_context,
      back: var_back,
      reshaped: var_reshaped,
      note: var_note,
      image: var_image,
      imageBack: var_imageBack,
      at: var_at,
    );
  }

  @protected
  CheckFeedback sse_decode_check_feedback(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_results = sse_decode_list_typed_result(deserializer);
    var var_passed = sse_decode_bool(deserializer);
    return CheckFeedback(results: var_results, passed: var_passed);
  }

  @protected
  ChoiceFeedback sse_decode_choice_feedback(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chosen = sse_decode_usize(deserializer);
    var var_correct = sse_decode_usize(deserializer);
    var var_passed = sse_decode_bool(deserializer);
    return ChoiceFeedback(
      chosen: var_chosen,
      correct: var_correct,
      passed: var_passed,
    );
  }

  @protected
  DeckEntry sse_decode_deck_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_isWorkspace = sse_decode_bool(deserializer);
    var var_due = sse_decode_bool(deserializer);
    var var_isTrace = sse_decode_bool(deserializer);
    return DeckEntry(
      title: var_title,
      path: var_path,
      isWorkspace: var_isWorkspace,
      due: var_due,
      isTrace: var_isTrace,
    );
  }

  @protected
  Depth sse_decode_depth(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Depth.values[inner];
  }

  @protected
  ForeignWriter sse_decode_foreign_writer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_device = sse_decode_String(deserializer);
    var var_ageMs = sse_decode_u_64(deserializer);
    return ForeignWriter(device: var_device, ageMs: var_ageMs);
  }

  @protected
  Grade sse_decode_grade(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Grade.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Input sse_decode_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Input.values[inner];
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DeckEntry> sse_decode_list_deck_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DeckEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_deck_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<NoteUnit> sse_decode_list_note_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NoteUnit>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_note_unit(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TypedResult> sse_decode_list_typed_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TypedResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_typed_result(deserializer));
    }
    return ans_;
  }

  @protected
  Mode sse_decode_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Mode.values[inner];
  }

  @protected
  NoteUnit sse_decode_note_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_text = sse_decode_String(deserializer);
        return NoteUnit_Sentence(text: var_text);
      case 1:
        var var_lines = sse_decode_list_String(deserializer);
        return NoteUnit_Code(lines: var_lines);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  CardView? sse_decode_opt_box_autoadd_card_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_card_view(deserializer));
    } else {
      return null;
    }
  }

  @protected
  CheckFeedback? sse_decode_opt_box_autoadd_check_feedback(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_check_feedback(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ChoiceFeedback? sse_decode_opt_box_autoadd_choice_feedback(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_choice_feedback(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Depth? sse_decode_opt_box_autoadd_depth(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_depth(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ForeignWriter? sse_decode_opt_box_autoadd_foreign_writer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_foreign_writer(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TutorCard? sse_decode_opt_box_autoadd_tutor_card(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_tutor_card(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ReviewState sse_decode_review_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_card = sse_decode_opt_box_autoadd_card_view(deserializer);
    var var_mode = sse_decode_mode(deserializer);
    var var_depth = sse_decode_depth(deserializer);
    var var_acquire = sse_decode_bool(deserializer);
    var var_choices = sse_decode_opt_list_String(deserializer);
    var var_keypoints = sse_decode_opt_list_String(deserializer);
    var var_input = sse_decode_input(deserializer);
    var var_finished = sse_decode_bool(deserializer);
    var var_remaining = sse_decode_u_32(deserializer);
    var var_initial = sse_decode_u_32(deserializer);
    var var_reviews = sse_decode_u_32(deserializer);
    var var_passed = sse_decode_u_32(deserializer);
    var var_failed = sse_decode_u_32(deserializer);
    var var_acquired = sse_decode_u_32(deserializer);
    var var_canRestart = sse_decode_bool(deserializer);
    var var_promotable = sse_decode_bool(deserializer);
    return ReviewState(
      card: var_card,
      mode: var_mode,
      depth: var_depth,
      acquire: var_acquire,
      choices: var_choices,
      keypoints: var_keypoints,
      input: var_input,
      finished: var_finished,
      remaining: var_remaining,
      initial: var_initial,
      reviews: var_reviews,
      passed: var_passed,
      failed: var_failed,
      acquired: var_acquired,
      canRestart: var_canRestart,
      promotable: var_promotable,
    );
  }

  @protected
  TutorCard sse_decode_tutor_card(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_subject = sse_decode_String(deserializer);
    var var_front = sse_decode_String(deserializer);
    var var_back = sse_decode_list_String(deserializer);
    var var_at = sse_decode_opt_String(deserializer);
    return TutorCard(
      subject: var_subject,
      front: var_front,
      back: var_back,
      at: var_at,
    );
  }

  @protected
  TypedResult sse_decode_typed_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_input = sse_decode_String(deserializer);
    var var_expected = sse_decode_String(deserializer);
    var var_passed = sse_decode_bool(deserializer);
    return TypedResult(
      input: var_input,
      expected: var_expected,
      passed: var_passed,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    ReviewSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ReviewSessionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    ReviewSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ReviewSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    ReviewSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ReviewSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReviewSession(
    ReviewSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ReviewSessionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_card_view(
    CardView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_card_view(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_check_feedback(
    CheckFeedback self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_check_feedback(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_choice_feedback(
    ChoiceFeedback self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_choice_feedback(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_depth(Depth self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_depth(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_foreign_writer(
    ForeignWriter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_foreign_writer(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_tutor_card(
    TutorCard self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_tutor_card(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_card_view(CardView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.front, serializer);
    sse_encode_list_String(self.context, serializer);
    sse_encode_list_String(self.back, serializer);
    sse_encode_bool(self.reshaped, serializer);
    sse_encode_list_note_unit(self.note, serializer);
    sse_encode_opt_String(self.image, serializer);
    sse_encode_opt_String(self.imageBack, serializer);
    sse_encode_opt_String(self.at, serializer);
  }

  @protected
  void sse_encode_check_feedback(CheckFeedback self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_typed_result(self.results, serializer);
    sse_encode_bool(self.passed, serializer);
  }

  @protected
  void sse_encode_choice_feedback(
    ChoiceFeedback self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.chosen, serializer);
    sse_encode_usize(self.correct, serializer);
    sse_encode_bool(self.passed, serializer);
  }

  @protected
  void sse_encode_deck_entry(DeckEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.isWorkspace, serializer);
    sse_encode_bool(self.due, serializer);
    sse_encode_bool(self.isTrace, serializer);
  }

  @protected
  void sse_encode_depth(Depth self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_foreign_writer(ForeignWriter self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.device, serializer);
    sse_encode_u_64(self.ageMs, serializer);
  }

  @protected
  void sse_encode_grade(Grade self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_input(Input self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_deck_entry(
    List<DeckEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_deck_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_note_unit(
    List<NoteUnit> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_note_unit(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_typed_result(
    List<TypedResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_typed_result(item, serializer);
    }
  }

  @protected
  void sse_encode_mode(Mode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_note_unit(NoteUnit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case NoteUnit_Sentence(text: final text):
        sse_encode_i_32(0, serializer);
        sse_encode_String(text, serializer);
      case NoteUnit_Code(lines: final lines):
        sse_encode_i_32(1, serializer);
        sse_encode_list_String(lines, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_card_view(
    CardView? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_card_view(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_check_feedback(
    CheckFeedback? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_check_feedback(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_choice_feedback(
    ChoiceFeedback? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_choice_feedback(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_depth(Depth? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_depth(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_foreign_writer(
    ForeignWriter? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_foreign_writer(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_tutor_card(
    TutorCard? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_tutor_card(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_String(
    List<String>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_review_state(ReviewState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_card_view(self.card, serializer);
    sse_encode_mode(self.mode, serializer);
    sse_encode_depth(self.depth, serializer);
    sse_encode_bool(self.acquire, serializer);
    sse_encode_opt_list_String(self.choices, serializer);
    sse_encode_opt_list_String(self.keypoints, serializer);
    sse_encode_input(self.input, serializer);
    sse_encode_bool(self.finished, serializer);
    sse_encode_u_32(self.remaining, serializer);
    sse_encode_u_32(self.initial, serializer);
    sse_encode_u_32(self.reviews, serializer);
    sse_encode_u_32(self.passed, serializer);
    sse_encode_u_32(self.failed, serializer);
    sse_encode_u_32(self.acquired, serializer);
    sse_encode_bool(self.canRestart, serializer);
    sse_encode_bool(self.promotable, serializer);
  }

  @protected
  void sse_encode_tutor_card(TutorCard self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.subject, serializer);
    sse_encode_String(self.front, serializer);
    sse_encode_list_String(self.back, serializer);
    sse_encode_opt_String(self.at, serializer);
  }

  @protected
  void sse_encode_typed_result(TypedResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.input, serializer);
    sse_encode_String(self.expected, serializer);
    sse_encode_bool(self.passed, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class ReviewSessionImpl extends RustOpaque implements ReviewSession {
  // Not to be used by end users
  ReviewSessionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ReviewSessionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ReviewSession,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ReviewSession,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ReviewSessionPtr,
  );

  /// Mark the current never-seen card as acquired (first exposure, no
  /// grade) and persist, returning the next position.
  ReviewState acquire({BigInt? nowMs}) => RustLib.instance.api
      .crateApiReviewReviewSessionAcquire(that: this, nowMs: nowMs);

  /// Records a PASSED remote exam sitting as this deck's mastery, mirroring
  /// the browser exam's own persistence. Callers must never call this on a
  /// fail: a failed fact-deck exam writes nothing on the phone.
  void applyExamPassed({required BigInt nowMs}) => RustLib.instance.api
      .crateApiReviewReviewSessionApplyExamPassed(that: this, nowMs: nowMs);

  /// Turns cleaned remediation deck-text (a failed remote exam's gaps)
  /// into virtual cards in the phone's own store, deduping against this
  /// deck's own cards and any already-stored virtuals
  /// (`alix::store::store_remediation_cards`, which saves internally, not
  /// saved again here). Returns how many cards were created or revived.
  ///
  /// `retire_after`: the bridge has no way today to read a session's
  /// resolved `[review] retire_after` cap back out of `alix::session::Session`
  /// (it holds no public accessor), so this passes `None`: the phone
  /// applies no retire cap in v1, rather than guess a value.
  int applyRemediation({required String cardsText, required BigInt nowMs}) =>
      RustLib.instance.api.crateApiReviewReviewSessionApplyRemediation(
        that: this,
        cardsText: cardsText,
        nowMs: nowMs,
      );

  /// Check typed lines against the current card (pure evidence; the
  /// learner-final grade is still a separate `grade` call).
  CheckFeedback? check({required List<String> lines}) => RustLib.instance.api
      .crateApiReviewReviewSessionCheck(that: this, lines: lines);

  /// Grade a pick against the same options `state` served; `None` when no
  /// pick is up. The learner-final grade is still a separate `grade` call.
  ChoiceFeedback? choose({required int chosen}) => RustLib.instance.api
      .crateApiReviewReviewSessionChoose(that: this, chosen: chosen);

  /// Whether this deck sits an AI exam (the flag `open` captured).
  bool deckHasExam() =>
      RustLib.instance.api.crateApiReviewReviewSessionDeckHasExam(that: this);

  /// The device that last wrote this session's store, when it was another
  /// one within the lib's warn window: the "review on one device at a
  /// time" banner's data. `now_ms` injects the clock (tests).
  ForeignWriter? foreignWriter({BigInt? nowMs}) => RustLib.instance.api
      .crateApiReviewReviewSessionForeignWriter(that: this, nowMs: nowMs);

  /// Grade the current card and persist, returning the next position.
  ReviewState grade({required Grade grade, BigInt? nowMs}) => RustLib
      .instance
      .api
      .crateApiReviewReviewSessionGrade(that: this, grade: grade, nowMs: nowMs);

  /// Mints a free-standing Tutor virtual card from an edited front/back,
  /// mirroring the web mint handler (`POST /api/ask/card/create`,
  /// `src/serve/mod.rs`): same validation and the same dedup against the
  /// session's own deck cards and any already-minted virtuals
  /// (`alix::store::mint_tutor_card`), then saves. Errors (malformed
  /// input, a duplicate of an existing card, or no card current to mint
  /// against) surface as the message text. Returns the new card's id,
  /// rendered as a string (the handler exposes nothing richer).
  String mintTutorCard({
    required String front,
    required List<String> back,
    required BigInt nowMs,
  }) => RustLib.instance.api.crateApiReviewReviewSessionMintTutorCard(
    that: this,
    front: front,
    back: back,
    nowMs: nowMs,
  );

  /// The current review position, for the screen to render. `now_ms`
  /// injects the clock behind the restartability check (tests); `None` is
  /// the wall clock.
  ReviewState state({BigInt? nowMs}) => RustLib.instance.api
      .crateApiReviewReviewSessionState(that: this, nowMs: nowMs);

  /// The current card's authored fields for the remote tutor to ground its
  /// answer on, never the masked [`CardView`] a cloze review renders.
  /// `None` when no card is current.
  TutorCard? tutorCard() =>
      RustLib.instance.api.crateApiReviewReviewSessionTutorCard(that: this);
}
