#!/usr/bin/env python3
"""Regenerate src/entities.rs from the canonical WHATWG entities.json.

Usage: python3 tools/gen-entities.py  (from the repository root)

Fetches https://html.spec.whatwg.org/entities.json, keeps only the
semicolon-terminated names (the ones CommonMark decodes), and rewrites
src/entities.rs deterministically: the hand-authored decoder and its
tests come from the template below, the table is sorted by name. Never
edit src/entities.rs by hand; edit this script and regenerate.
"""

import json
import pathlib
import sys
import urllib.request

URL = "https://html.spec.whatwg.org/entities.json"
OUT = pathlib.Path(__file__).resolve().parent.parent / "src" / "entities.rs"

PREAMBLE = '''// GENERATED by tools/gen-entities.py from the WHATWG entities.json;
// do not edit by hand, regenerate instead.

use std::borrow::Cow;

/// Decodes the HTML5 named (`&amp;`), decimal (`&#65;`), and hex
/// (`&#x41;`) entity forms; everything that is not a complete, valid
/// entity stays literal. U+0000, surrogates, and out-of-range code
/// points decode to U+FFFD. Production decodes per glyph through
/// `entity_at`; this string form exists for the law tests.
#[cfg(test)]
pub(crate) fn decode_entities(text: &str) -> String {
    if !text.contains('&') {
        return text.to_string();
    }
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(amp) = rest.find('&') {
        out.push_str(&rest[..amp]);
        let tail = &rest[amp..];
        match entity_at(tail) {
            Some((consumed, replacement)) => {
                out.push_str(&replacement);
                rest = &tail[consumed..];
            }
            None => {
                out.push('&');
                rest = &tail[1..];
            }
        }
    }
    out.push_str(rest);
    out
}

/// The byte length and replacement of the entity starting at `tail`'s
/// leading `&`, or None when what follows is not a complete entity.
pub(crate) fn entity_at(tail: &str) -> Option<(usize, Cow<'static, str>)> {
    let body = &tail[1..];
    if let Some(numeric) = body.strip_prefix('#') {
        let (digits, radix, prefix_len) = match numeric.strip_prefix(['x', 'X']) {
            Some(hex) => (hex, 16, 3),
            None => (numeric, 10, 2),
        };
        let max_digits = if radix == 16 { 6 } else { 7 };
        let run = digits.chars().take_while(|ch| ch.is_digit(radix)).count();
        if run == 0 || run > max_digits || !digits[run..].starts_with(';') {
            return None;
        }
        let value = u32::from_str_radix(&digits[..run], radix).ok()?;
        let point = match value {
            0 => '\\u{FFFD}',
            _ => char::from_u32(value).unwrap_or('\\u{FFFD}'),
        };
        return Some((prefix_len + run + 1, Cow::Owned(point.to_string())));
    }
    let name_len = body
        .chars()
        .take(64)
        .take_while(|ch| ch.is_ascii_alphanumeric())
        .count();
    if name_len == 0 || !body[name_len..].starts_with(';') {
        return None;
    }
    let name = &body[..name_len];
    let index = ENTITIES
        .binary_search_by(|(candidate, _)| (*candidate).cmp(name))
        .ok()?;
    Some((1 + name_len + 1, Cow::Borrowed(ENTITIES[index].1)))
}
'''

TESTS = '''
#[cfg(test)]
mod tests {
    use super::decode_entities;

    #[test]
    fn entity_decoding_follows_the_commonmark_grammar_row_by_row() {
        let rows = [
            ("&amp;", "&", "a named entity"),
            (
                "&NotEqualTilde;",
                "\\u{2242}\\u{338}",
                "a multi-codepoint named entity",
            ),
            ("&bsol;", "\\\\", "a backslash replacement survives"),
            ("&#65;", "A", "a decimal entity"),
            ("&#x41;", "A", "a hex entity"),
            ("&#X41;", "A", "the uppercase hex marker"),
            ("&#128512;", "\\u{1F600}", "an astral decimal entity"),
            ("&#0;", "\\u{FFFD}", "zero becomes the replacement character"),
            (
                "&#xD800;",
                "\\u{FFFD}",
                "a surrogate becomes the replacement",
            ),
            (
                "&#1114112;",
                "\\u{FFFD}",
                "out of range becomes the replacement",
            ),
            (
                "&noSuchEntity;",
                "&noSuchEntity;",
                "an unknown name stays literal",
            ),
            ("&amp", "&amp", "a missing semicolon stays literal"),
            ("a & b", "a & b", "a bare ampersand stays literal"),
            ("&#;", "&#;", "empty digits stay literal"),
            ("&#x;", "&#x;", "empty hex digits stay literal"),
            (
                "&#12345678;",
                "&#12345678;",
                "eight decimal digits stay literal",
            ),
            (
                "&#x1234567;",
                "&#x1234567;",
                "seven hex digits stay literal",
            ),
            (
                "&lt;div&gt;",
                "<div>",
                "decoded brackets are text, never a tag",
            ),
            ("&amp;&lt;", "&<", "adjacent entities both decode"),
            ("plain text", "plain text", "the no-ampersand fast path"),
        ];
        for (input, expected, why) in rows {
            assert_eq!(decode_entities(input), expected, "{why}: {input}");
        }
    }

    #[test]
    fn the_table_is_sorted_and_binary_searchable() {
        assert!(
            super::ENTITIES.windows(2).all(|pair| pair[0].0 < pair[1].0),
            "the generated table must stay strictly sorted by name"
        );
        assert!(
            super::ENTITIES.len() > 2000,
            "the full named set is present"
        );
    }
}
'''


def rust_string(value: str) -> str:
    return '"' + "".join(f"\\u{{{ord(ch):X}}}" for ch in value) + '"'


def main() -> int:
    with urllib.request.urlopen(URL, timeout=30) as response:
        data = json.load(response)
    rows = sorted(
        (name[1:-1], entry["characters"])
        for name, entry in data.items()
        if name.startswith("&") and name.endswith(";")
    )
    lines = [PREAMBLE]
    lines.append(f"static ENTITIES: [(&str, &str); {len(rows)}] = [\n")
    for name, characters in rows:
        lines.append(f'    ("{name}", {rust_string(characters)}),\n')
    lines.append("];\n")
    lines.append(TESTS)
    OUT.write_text("".join(lines))
    print(f"wrote {OUT} with {len(rows)} entities")
    return 0


if __name__ == "__main__":
    sys.exit(main())
