// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Writes `text` into `decks_dir`, choosing a collision-free name from
/// `filename`: strip a trailing `.txt` to get the base stem, then try
/// `<stem>.txt`, `<stem>-2.txt`, `<stem>-3.txt`, ... until one is free. A
/// single-user phone has no concurrent writer, so an exists-check loop
/// followed by one `place_deck` call is enough; `place_deck` re-checks and
/// still bails on a genuine TOCTOU race, which is left to propagate as an
/// error rather than retried. Returns the actual written file name (never
/// the pre-checked candidate) so Dart can show "saved as <name>" and refresh
/// the picker. A freshly generated deck that fails to parse is still saved
/// by `place_deck` (lenient by design, fixable by hand) -- this function
/// does not fail or otherwise surface that case, matching the spec's plain
/// `String` return.
String applyGeneratedDeck({
  required String decksDir,
  required String filename,
  required String text,
}) => RustLib.instance.api.crateApiGenerateApplyGeneratedDeck(
  decksDir: decksDir,
  filename: filename,
  text: text,
);
