// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'review.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Lists the decks root. `now_ms` injects the clock (tests); `None` is now.
List<DeckEntry> listRoot({required String root, BigInt? nowMs}) =>
    RustLib.instance.api.crateApiListingListRoot(root: root, nowMs: nowMs);

/// Syncthing conflict copies next to any store under `root`: non-empty
/// means two devices wrote concurrently and the picker should warn before
/// the user reviews on top of a fork.
List<String> syncConflicts({required String root}) =>
    RustLib.instance.api.crateApiListingSyncConflicts(root: root);

/// Lists one drillable folder of the root.
List<DeckEntry> listMembers({
  required String root,
  required String dir,
  BigInt? nowMs,
}) => RustLib.instance.api.crateApiListingListMembers(
  root: root,
  dir: dir,
  nowMs: nowMs,
);

/// One row of a folder listing, as the picker screen renders it.
class DeckEntry {
  final String title;
  final String path;

  /// Drillable: list its members with [`list_members`].
  final bool isWorkspace;

  /// Anything to do right now, against the store this entry reviews into.
  final bool due;

  /// A trace deck (`% trace:`): opens a walk (`WalkSession`), not a card
  /// review; the flag lets the picker route the row to the walk screen
  /// instead of a review session.
  final bool isTrace;

  /// The session depth remembered for this deck, else its fresh-session
  /// default. Deck rows only.
  final Depth lastDepth;

  /// Finished and exam-passed, mirroring the web picker's mastered badge.
  /// Deck rows only.
  final bool mastered;

  /// Drilled and awaiting its AI exam. Deck rows only.
  final bool examDue;

  /// The deck has an AI exam at all (a sourced fact deck, or a trace).
  /// Deck rows only.
  final bool hasExam;

  /// A `% requires:` prerequisite isn't finished, mirroring the web
  /// picker's lock icon. Deck rows only.
  final bool locked;

  /// The workspace's resolved picker icon file, mirroring the web
  /// picker's emblem. Workspace/folder rows only; `None` otherwise.
  final String? icon;

  /// Nesting depth in the workspace's dependency tree. Member rows only;
  /// `0` otherwise.
  final int indent;

  /// The branch-line prefix (`├─`/`└─`/`│`) for this row in the
  /// workspace's dependency tree. Member rows only; empty otherwise.
  final String tree;

  const DeckEntry({
    required this.title,
    required this.path,
    required this.isWorkspace,
    required this.due,
    required this.isTrace,
    required this.lastDepth,
    required this.mastered,
    required this.examDue,
    required this.hasExam,
    required this.locked,
    this.icon,
    required this.indent,
    required this.tree,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      path.hashCode ^
      isWorkspace.hashCode ^
      due.hashCode ^
      isTrace.hashCode ^
      lastDepth.hashCode ^
      mastered.hashCode ^
      examDue.hashCode ^
      hasExam.hashCode ^
      locked.hashCode ^
      icon.hashCode ^
      indent.hashCode ^
      tree.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeckEntry &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          path == other.path &&
          isWorkspace == other.isWorkspace &&
          due == other.due &&
          isTrace == other.isTrace &&
          lastDepth == other.lastDepth &&
          mastered == other.mastered &&
          examDue == other.examDue &&
          hasExam == other.hasExam &&
          locked == other.locked &&
          icon == other.icon &&
          indent == other.indent &&
          tree == other.tree;
}
