// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Lists the decks root. `now_ms` injects the clock (tests); `None` is now.
List<DeckEntry> listRoot({required String root, BigInt? nowMs}) =>
    RustLib.instance.api.crateApiListingListRoot(root: root, nowMs: nowMs);

/// Syncthing conflict copies next to any store under `root`: non-empty
/// means two devices wrote concurrently and the picker should warn before
/// the user reviews on top of a fork.
List<String> syncConflicts({required String root}) =>
    RustLib.instance.api.crateApiListingSyncConflicts(root: root);

/// Lists one drillable folder of the root.
List<DeckEntry> listMembers({
  required String root,
  required String dir,
  BigInt? nowMs,
}) => RustLib.instance.api.crateApiListingListMembers(
  root: root,
  dir: dir,
  nowMs: nowMs,
);

/// One row of a folder listing, as the picker screen renders it.
class DeckEntry {
  final String title;
  final String path;

  /// Drillable: list its members with [`list_members`].
  final bool isWorkspace;

  /// Anything to do right now, against the store this entry reviews into.
  final bool due;

  const DeckEntry({
    required this.title,
    required this.path,
    required this.isWorkspace,
    required this.due,
  });

  @override
  int get hashCode =>
      title.hashCode ^ path.hashCode ^ isWorkspace.hashCode ^ due.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeckEntry &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          path == other.path &&
          isWorkspace == other.isWorkspace &&
          due == other.due;
}
