// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'review.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`, `from`, `from`

/// The Explain checklist tally as a grade: none covered fails, all pass,
/// some is a partial. The rule lives in core (`scheduler::keypoint_grade`);
/// this is only the bridge.
Grade keypointGrade({required int covered, required int total}) => RustLib
    .instance
    .api
    .crateApiReviewKeypointGrade(covered: covered, total: total);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ReviewSession>>
abstract class ReviewSession implements RustOpaqueInterface {
  /// Mark the current never-seen card as acquired (first exposure, no
  /// grade) and persist, returning the next position.
  ReviewState acquire({BigInt? nowMs});

  /// Check typed lines against the current card (pure evidence; the
  /// learner-final grade is still a separate `grade` call).
  CheckFeedback? check({required List<String> lines});

  /// Grade a pick against the same options `state` served; `None` when no
  /// pick is up. The learner-final grade is still a separate `grade` call.
  ChoiceFeedback? choose({required int chosen});

  /// The device that last wrote this session's store, when it was another
  /// one within the lib's warn window: the "review on one device at a
  /// time" banner's data. `now_ms` injects the clock (tests).
  ForeignWriter? foreignWriter({BigInt? nowMs});

  /// Grade the current card and persist, returning the next position.
  ReviewState grade({required Grade grade, BigInt? nowMs});

  /// Open a deck of the decks folder `root_dir` at `depth` (default:
  /// the deck's last depth, else Recall). The progress store is routed the
  /// way the web and CLI route it: a workspace member reviews into its
  /// workspace's own store, everything else into the root's shared store.
  /// `now_ms` injects the session clock (tests); `None` is the wall clock.
  /// `device` names this device in the store's last-writer marker (the
  /// app passes its settings.json label); `None` keeps whatever the core
  /// derived for this machine.
  static ReviewSession open({
    required String deckPath,
    required String rootDir,
    Depth? depth,
    BigInt? nowMs,
    String? device,
  }) => RustLib.instance.api.crateApiReviewReviewSessionOpen(
    deckPath: deckPath,
    rootDir: rootDir,
    depth: depth,
    nowMs: nowMs,
    device: device,
  );

  /// The current review position, for the screen to render. `now_ms`
  /// injects the clock behind the restartability check (tests); `None` is
  /// the wall clock.
  ReviewState state({BigInt? nowMs});
}

class CardView {
  final String front;
  final List<String> context;
  final List<String> back;
  final bool reshaped;
  final List<NoteUnit> note;
  final String? image;
  final String? imageBack;
  final String? at;

  const CardView({
    required this.front,
    required this.context,
    required this.back,
    required this.reshaped,
    required this.note,
    this.image,
    this.imageBack,
    this.at,
  });

  @override
  int get hashCode =>
      front.hashCode ^
      context.hashCode ^
      back.hashCode ^
      reshaped.hashCode ^
      note.hashCode ^
      image.hashCode ^
      imageBack.hashCode ^
      at.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CardView &&
          runtimeType == other.runtimeType &&
          front == other.front &&
          context == other.context &&
          back == other.back &&
          reshaped == other.reshaped &&
          note == other.note &&
          image == other.image &&
          imageBack == other.imageBack &&
          at == other.at;
}

class CheckFeedback {
  final List<TypedResult> results;
  final bool passed;

  const CheckFeedback({required this.results, required this.passed});

  @override
  int get hashCode => results.hashCode ^ passed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CheckFeedback &&
          runtimeType == other.runtimeType &&
          results == other.results &&
          passed == other.passed;
}

class ChoiceFeedback {
  final BigInt chosen;
  final BigInt correct;
  final bool passed;

  const ChoiceFeedback({
    required this.chosen,
    required this.correct,
    required this.passed,
  });

  @override
  int get hashCode => chosen.hashCode ^ correct.hashCode ^ passed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChoiceFeedback &&
          runtimeType == other.runtimeType &&
          chosen == other.chosen &&
          correct == other.correct &&
          passed == other.passed;
}

enum Depth { recognize, recall, reconstruct }

/// Another device's recent write of this session's store (see
/// [`ReviewSession::foreign_writer`]): the roaming-discipline banner's data.
class ForeignWriter {
  /// The other device's label.
  final String device;

  /// How long ago it wrote, in ms.
  final BigInt ageMs;

  const ForeignWriter({required this.device, required this.ageMs});

  @override
  int get hashCode => device.hashCode ^ ageMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ForeignWriter &&
          runtimeType == other.runtimeType &&
          device == other.device &&
          ageMs == other.ageMs;
}

/// The learner's self-grade, mirrored so frb bridges it from this crate.
enum Grade { fail, partial, pass }

enum Input { type, draw }

/// frb mirrors of the core contract types (they live in the `alix` crate,
/// which frb does not scan): field-for-field copies that teach the generator
/// their shape so Dart gets real classes and enums, not opaque handles. Keep
/// in lock step with `alix::review`, `alix::answer`, and `alix::depth`.
enum Mode { flip, typing, typeLine, choice, lineByLine, explain }

@freezed
sealed class NoteUnit with _$NoteUnit {
  const NoteUnit._();

  const factory NoteUnit.sentence({required String text}) = NoteUnit_Sentence;
  const factory NoteUnit.code({required List<String> lines}) = NoteUnit_Code;
}

class ReviewState {
  final CardView? card;
  final Mode mode;
  final Depth depth;
  final bool acquire;
  final List<String>? choices;
  final List<String>? keypoints;
  final Input input;
  final bool finished;
  final int remaining;
  final int initial;
  final int reviews;
  final int passed;
  final int failed;
  final bool canRestart;
  final bool promotable;

  const ReviewState({
    this.card,
    required this.mode,
    required this.depth,
    required this.acquire,
    this.choices,
    this.keypoints,
    required this.input,
    required this.finished,
    required this.remaining,
    required this.initial,
    required this.reviews,
    required this.passed,
    required this.failed,
    required this.canRestart,
    required this.promotable,
  });

  @override
  int get hashCode =>
      card.hashCode ^
      mode.hashCode ^
      depth.hashCode ^
      acquire.hashCode ^
      choices.hashCode ^
      keypoints.hashCode ^
      input.hashCode ^
      finished.hashCode ^
      remaining.hashCode ^
      initial.hashCode ^
      reviews.hashCode ^
      passed.hashCode ^
      failed.hashCode ^
      canRestart.hashCode ^
      promotable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewState &&
          runtimeType == other.runtimeType &&
          card == other.card &&
          mode == other.mode &&
          depth == other.depth &&
          acquire == other.acquire &&
          choices == other.choices &&
          keypoints == other.keypoints &&
          input == other.input &&
          finished == other.finished &&
          remaining == other.remaining &&
          initial == other.initial &&
          reviews == other.reviews &&
          passed == other.passed &&
          failed == other.failed &&
          canRestart == other.canRestart &&
          promotable == other.promotable;
}

class TypedResult {
  final String input;
  final String expected;
  final bool passed;

  const TypedResult({
    required this.input,
    required this.expected,
    required this.passed,
  });

  @override
  int get hashCode => input.hashCode ^ expected.hashCode ^ passed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypedResult &&
          runtimeType == other.runtimeType &&
          input == other.input &&
          expected == other.expected &&
          passed == other.passed;
}
