// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'review.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `walk_excerpt`, `walk_state`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

Grade keypointGrade({required int covered, required int total}) => RustLib
    .instance
    .api
    .crateApiReviewKeypointGrade(covered: covered, total: total);

void seedChoiceDistractors({
  required String deckPath,
  required String rootDir,
}) => RustLib.instance.api.crateApiReviewSeedChoiceDistractors(
  deckPath: deckPath,
  rootDir: rootDir,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ReviewSession>>
abstract class ReviewSession implements RustOpaqueInterface {
  ReviewState acquire({BigInt? nowMs});

  void applyCardNote({required int line, required List<String> notes});

  void applyExamPassed({required BigInt nowMs});

  int applyRemediation({required String cardsText, required BigInt nowMs});

  CheckFeedback? check({required List<String> lines});

  ChoiceFeedback? choose({required int chosen});

  CrumbState? crumb({BigInt? nowMs});

  bool deckHasExam();

  ForeignWriter? foreignWriter({BigInt? nowMs});

  ReviewState grade({required Grade grade, BigInt? nowMs});

  String mintTutorCard({
    required String front,
    required List<String> back,
    required BigInt nowMs,
  });

  static ReviewSession open({
    required String deckPath,
    required String rootDir,
    Depth? depth,
    BigInt? nowMs,
    String? device,
  }) => RustLib.instance.api.crateApiReviewReviewSessionOpen(
    deckPath: deckPath,
    rootDir: rootDir,
    depth: depth,
    nowMs: nowMs,
    device: device,
  );

  ReviewState state({BigInt? nowMs});

  TutorCard? tutorCard();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WalkSession>>
abstract class WalkSession implements RustOpaqueInterface {
  void applyExamFailed({required BigInt nowMs});

  void applyExamPassed({required BigInt nowMs});

  bool deckHasExam();

  BigInt? examCooldownMs({required BigInt nowMs});

  WalkState grade({required WalkDelta delta, BigInt? nowMs});

  static WalkSession open({
    required String deckPath,
    required String rootDir,
    BigInt? nowMs,
    String? device,
  }) => RustLib.instance.api.crateApiReviewWalkSessionOpen(
    deckPath: deckPath,
    rootDir: rootDir,
    nowMs: nowMs,
    device: device,
  );

  void predict({required String text});

  WalkState state();
}

class CardView {
  final String front;
  final List<InlineRun> frontRuns;
  final List<NoteUnit>? frontUnits;
  final List<String> context;
  final List<List<InlineRun>> contextRuns;
  final List<String> back;
  final List<List<InlineRun>> backRuns;
  final bool reshaped;
  final List<NoteUnit> note;
  final List<ImageView> images;
  final List<ImageView> imagesBack;
  final String? at;

  const CardView({
    required this.front,
    required this.frontRuns,
    this.frontUnits,
    required this.context,
    required this.contextRuns,
    required this.back,
    required this.backRuns,
    required this.reshaped,
    required this.note,
    required this.images,
    required this.imagesBack,
    this.at,
  });

  @override
  int get hashCode =>
      front.hashCode ^
      frontRuns.hashCode ^
      frontUnits.hashCode ^
      context.hashCode ^
      contextRuns.hashCode ^
      back.hashCode ^
      backRuns.hashCode ^
      reshaped.hashCode ^
      note.hashCode ^
      images.hashCode ^
      imagesBack.hashCode ^
      at.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CardView &&
          runtimeType == other.runtimeType &&
          front == other.front &&
          frontRuns == other.frontRuns &&
          frontUnits == other.frontUnits &&
          context == other.context &&
          contextRuns == other.contextRuns &&
          back == other.back &&
          backRuns == other.backRuns &&
          reshaped == other.reshaped &&
          note == other.note &&
          images == other.images &&
          imagesBack == other.imagesBack &&
          at == other.at;
}

class CheckFeedback {
  final List<TypedResult> results;
  final bool passed;

  const CheckFeedback({required this.results, required this.passed});

  @override
  int get hashCode => results.hashCode ^ passed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CheckFeedback &&
          runtimeType == other.runtimeType &&
          results == other.results &&
          passed == other.passed;
}

class ChecklistItem {
  final bool checked;
  final String text;
  final List<InlineRun> runs;

  const ChecklistItem({
    required this.checked,
    required this.text,
    required this.runs,
  });

  @override
  int get hashCode => checked.hashCode ^ text.hashCode ^ runs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChecklistItem &&
          runtimeType == other.runtimeType &&
          checked == other.checked &&
          text == other.text &&
          runs == other.runs;
}

class ChoiceFeedback {
  final BigInt chosen;
  final BigInt correct;
  final bool passed;

  const ChoiceFeedback({
    required this.chosen,
    required this.correct,
    required this.passed,
  });

  @override
  int get hashCode => chosen.hashCode ^ correct.hashCode ^ passed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChoiceFeedback &&
          runtimeType == other.runtimeType &&
          chosen == other.chosen &&
          correct == other.correct &&
          passed == other.passed;
}

class CrumbState {
  final List<String> regions;
  final int current;
  final List<Float32List> cells;

  const CrumbState({
    required this.regions,
    required this.current,
    required this.cells,
  });

  @override
  int get hashCode => regions.hashCode ^ current.hashCode ^ cells.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CrumbState &&
          runtimeType == other.runtimeType &&
          regions == other.regions &&
          current == other.current &&
          cells == other.cells;
}

enum Depth { recognize, recall, reconstruct }

class ForeignWriter {
  final String device;
  final BigInt ageMs;

  const ForeignWriter({required this.device, required this.ageMs});

  @override
  int get hashCode => device.hashCode ^ ageMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ForeignWriter &&
          runtimeType == other.runtimeType &&
          device == other.device &&
          ageMs == other.ageMs;
}

enum Grade { fail, partial, pass }

class ImageView {
  final String src;
  final String? alt;

  const ImageView({required this.src, this.alt});

  @override
  int get hashCode => src.hashCode ^ alt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageView &&
          runtimeType == other.runtimeType &&
          src == other.src &&
          alt == other.alt;
}

class InlineRun {
  final String text;
  final bool bold;
  final bool italic;
  final bool code;
  final MathView? math;

  const InlineRun({
    required this.text,
    required this.bold,
    required this.italic,
    required this.code,
    this.math,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      bold.hashCode ^
      italic.hashCode ^
      code.hashCode ^
      math.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InlineRun &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          bold == other.bold &&
          italic == other.italic &&
          code == other.code &&
          math == other.math;
}

enum Input { type, draw }

class MathView {
  final bool display;
  final String? svg;
  final String? error;

  const MathView({required this.display, this.svg, this.error});

  @override
  int get hashCode => display.hashCode ^ svg.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MathView &&
          runtimeType == other.runtimeType &&
          display == other.display &&
          svg == other.svg &&
          error == other.error;
}

enum Mode { flip, typing, typeLine, choice, lineByLine, explain }

@freezed
sealed class NoteUnit with _$NoteUnit {
  const NoteUnit._();

  const factory NoteUnit.sentence({
    required String text,
    required List<InlineRun> runs,
  }) = NoteUnit_Sentence;
  const factory NoteUnit.code({required List<String> lines}) = NoteUnit_Code;
  const factory NoteUnit.checklist({required List<ChecklistItem> items}) =
      NoteUnit_Checklist;
}

class ReviewState {
  final CardView? card;
  final Mode mode;
  final Depth depth;
  final bool acquire;
  final List<String>? choices;
  final List<List<InlineRun>>? choiceRuns;
  final List<String>? keypoints;
  final List<List<InlineRun>>? keypointRuns;
  final Input input;
  final bool finished;
  final int remaining;
  final int initial;
  final int reviews;
  final int passed;
  final int failed;
  final int acquired;
  final bool canRestart;
  final bool promotable;

  const ReviewState({
    this.card,
    required this.mode,
    required this.depth,
    required this.acquire,
    this.choices,
    this.choiceRuns,
    this.keypoints,
    this.keypointRuns,
    required this.input,
    required this.finished,
    required this.remaining,
    required this.initial,
    required this.reviews,
    required this.passed,
    required this.failed,
    required this.acquired,
    required this.canRestart,
    required this.promotable,
  });

  @override
  int get hashCode =>
      card.hashCode ^
      mode.hashCode ^
      depth.hashCode ^
      acquire.hashCode ^
      choices.hashCode ^
      choiceRuns.hashCode ^
      keypoints.hashCode ^
      keypointRuns.hashCode ^
      input.hashCode ^
      finished.hashCode ^
      remaining.hashCode ^
      initial.hashCode ^
      reviews.hashCode ^
      passed.hashCode ^
      failed.hashCode ^
      acquired.hashCode ^
      canRestart.hashCode ^
      promotable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewState &&
          runtimeType == other.runtimeType &&
          card == other.card &&
          mode == other.mode &&
          depth == other.depth &&
          acquire == other.acquire &&
          choices == other.choices &&
          choiceRuns == other.choiceRuns &&
          keypoints == other.keypoints &&
          keypointRuns == other.keypointRuns &&
          input == other.input &&
          finished == other.finished &&
          remaining == other.remaining &&
          initial == other.initial &&
          reviews == other.reviews &&
          passed == other.passed &&
          failed == other.failed &&
          acquired == other.acquired &&
          canRestart == other.canRestart &&
          promotable == other.promotable;
}

class TutorCard {
  final String subject;
  final String front;
  final List<String> back;
  final String? at;
  final BigInt line;

  const TutorCard({
    required this.subject,
    required this.front,
    required this.back,
    this.at,
    required this.line,
  });

  @override
  int get hashCode =>
      subject.hashCode ^
      front.hashCode ^
      back.hashCode ^
      at.hashCode ^
      line.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TutorCard &&
          runtimeType == other.runtimeType &&
          subject == other.subject &&
          front == other.front &&
          back == other.back &&
          at == other.at &&
          line == other.line;
}

class TypedResult {
  final String input;
  final String expected;
  final bool passed;

  const TypedResult({
    required this.input,
    required this.expected,
    required this.passed,
  });

  @override
  int get hashCode => input.hashCode ^ expected.hashCode ^ passed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypedResult &&
          runtimeType == other.runtimeType &&
          input == other.input &&
          expected == other.expected &&
          passed == other.passed;
}

enum WalkDelta { missed, partly, got }

class WalkExcerpt {
  final String path;
  final List<WalkLine> lines;
  final bool truncated;

  const WalkExcerpt({
    required this.path,
    required this.lines,
    required this.truncated,
  });

  @override
  int get hashCode => path.hashCode ^ lines.hashCode ^ truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalkExcerpt &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          lines == other.lines &&
          truncated == other.truncated;
}

class WalkLine {
  final int n;
  final String text;

  const WalkLine({required this.n, required this.text});

  @override
  int get hashCode => n.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalkLine &&
          runtimeType == other.runtimeType &&
          n == other.n &&
          text == other.text;
}

enum WalkPhase { predict, reveal, done }

class WalkState {
  final WalkPhase phase;
  final String description;
  final String? source;
  final int total;
  final int current;
  final String? prompt;
  final List<String> givens;
  final String? locator;
  final String? prediction;
  final WalkExcerpt? excerpt;
  final String? excerptError;
  final List<String> points;
  final String? note;
  final WalkSummary? summary;

  const WalkState({
    required this.phase,
    required this.description,
    this.source,
    required this.total,
    required this.current,
    this.prompt,
    required this.givens,
    this.locator,
    this.prediction,
    this.excerpt,
    this.excerptError,
    required this.points,
    this.note,
    this.summary,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      description.hashCode ^
      source.hashCode ^
      total.hashCode ^
      current.hashCode ^
      prompt.hashCode ^
      givens.hashCode ^
      locator.hashCode ^
      prediction.hashCode ^
      excerpt.hashCode ^
      excerptError.hashCode ^
      points.hashCode ^
      note.hashCode ^
      summary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalkState &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          description == other.description &&
          source == other.source &&
          total == other.total &&
          current == other.current &&
          prompt == other.prompt &&
          givens == other.givens &&
          locator == other.locator &&
          prediction == other.prediction &&
          excerpt == other.excerpt &&
          excerptError == other.excerptError &&
          points == other.points &&
          note == other.note &&
          summary == other.summary;
}

class WalkSummary {
  final int passed;
  final int partly;
  final int failed;
  final Uint32List weak;
  final int total;

  const WalkSummary({
    required this.passed,
    required this.partly,
    required this.failed,
    required this.weak,
    required this.total,
  });

  @override
  int get hashCode =>
      passed.hashCode ^
      partly.hashCode ^
      failed.hashCode ^
      weak.hashCode ^
      total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalkSummary &&
          runtimeType == other.runtimeType &&
          passed == other.passed &&
          partly == other.partly &&
          failed == other.failed &&
          weak == other.weak &&
          total == other.total;
}
